---
title: "CreativeAssignmentFour"
author: "Whytne Stevens"
date: "10/3/2020"
output: 
  html_document:
    theme: cosmo
    toc: true
    toc_depth: 3
    toc_float: true
---
# Intro/Set Up

For this creative assignment, I was interested in looking at datasets from Chicago First I loaded relevant r libraries as well as other r libraries that might be useful to me later on and pulled a world map using the libraries loaded below.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load libraries, results = "hide", message = FALSE, warning = FALSE}
library(osmdata)
library(opentripplanner)
library(tidyverse)
library(sf)
library(ggthemes)
library(ggspatial)
library(wesanderson)
```



```{r load farmers markets}
dcfarmersmarkets<- st_read(
  "https://opendata.arcgis.com/datasets/f2e1c2ef9eb44f2899f4a310a80ecec9_2.kml")
```


```{r}
NAD83_Virginia_North <- "+proj=lcc +lat_1=39.2 +lat_2=38.03333333333333 +lat_0=37.66666666666666 +lon_0=-78.5 +x_0=3500000 +y_0=2000000 +ellps=GRS80 +units=m +no_defs"

dc_street_features <- opq(bbox = 'Washington DC USA') %>%
  add_osm_feature(key = 'highway') %>%
  osmdata_sf()

dc_streets <- dc_street_features$osm_lines %>%
  st_transform(crs = NAD83_Virginia_North)
```


```{r}
ggplot(dc_streets) +
  geom_sf() +
  theme_map()
```


```{r}
path_otp <- otp_dl_jar("OTP")
```


```{r}
path_data <- file.path(getwd(), "OTP")
path_otp <- paste(path_data, "otp.jar",sep = "/")

otp_build_graph(otp = path_otp, dir = path_data, memory = 1024) 
```


```{r}
otp_setup(otp = path_otp, dir = path_data, memory =1024)

#  Connect to opentripplanner

otpcon <- otp_connect()
```




```{r}
iso_5min_walk <- 
  otp_isochrone(otpcon = otpcon, fromPlace = dcfarmersmarkets, 
                mode = "WALK", cutoffSec = 300) %>%
  st_transform(crs = NAD83_Virginia_North
               ) %>%
  mutate(mode = "walk")

iso_5min_drive <- 
  otp_isochrone(otpcon = otpcon, fromPlace = dcfarmersmarkets, 
                mode = "CAR", cutoffSec = 300) %>%
  st_transform(crs = NAD83_Virginia_North) %>%
  mutate(mode = "drive")

iso_5min_bike <- 
  otp_isochrone(otpcon = otpcon, fromPlace = dcfarmersmarkets, 
                mode = "BICYCLE", cutoffSec = 300) %>%
  st_transform(crs = NAD83_Virginia_North) %>%
  mutate(mode = "bike")

iso_all_modes <- rbind(iso_5min_drive, iso_5min_walk, iso_5min_bike)

otp_stop()
```


```{r}
right_side <- st_bbox(iso_all_modes)$xmax
left_side  <- st_bbox(iso_all_modes)$xmin
top_side <- st_bbox(iso_all_modes)$ymax
bottom_side <- st_bbox(iso_all_modes)$ymin

ggplot(iso_all_modes) +
  annotation_map_tile(zoomin = 0, type = "stamenbw", progress = "none")  +
  geom_sf(aes(fill = mode), alpha = 0.5) +
  geom_sf(data = dcfarmersmarkets) +
  coord_sf(xlim = c(left_side, right_side), 
           ylim = c(bottom_side, top_side), expand = FALSE) +
  scale_fill_viridis_d(name = "Area that is reachable within 5 minutes",
                     labels = c("By car", "By foot", "By bike"),
                     option="plasma") +
  theme_map() +
  labs(caption = "Basemap Copyright OpenStreetMap contributors")
```






```{r}

```











