---
title: "CreativeAssignment6"
author: "Whytne Stevens"
date: "10/23/2020"
output: 
  html_document:
    theme: cosmo
    toc: true
    toc_depth: 3
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r load libraries, results = "hide", message = FALSE, warning = FALSE}
library(tidyverse)
library(sf)
library(leaflet)
library(htmltools)
library(htmlwidgets)
```



```{r load data, echo = FALSE}
commareaschi <-st_read("https://data.cityofchicago.org/api/geospatial/cauq-8yn6?method=export&format=GeoJSON")
```

```{r load chicago city boundary data, echo = FALSE}
cityboundarychi <-st_read("https://data.cityofchicago.org/api/geospatial/ewy2-6yfk?method=export&format=GeoJSON")
```

```{r}
commareaschi$describe <- 
  paste("Community Area Name:", commareaschi$community, "<br>", 
        "Community Area Number:", commareaschi$area_numbe, "<br>") %>% 
  lapply(htmltools::HTML)
```



## Murals in Chicago

You can also embed plots, for example:

```{r load chicago mural data, echo = FALSE}
muralschi <-st_read("https://data.cityofchicago.org/api/geospatial/we8h-apcf?method=export&format=GeoJSON")
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.


```{r}
muralschi$describe <- 
  paste("Title:", muralschi$artwork_title, "<br>", 
        "Artist:", muralschi$artist_credit, "<br>",
        "Year:", muralschi$year_installed, "<br>",
        "Location:", muralschi$street_address, "<br>") %>% 
  lapply(htmltools::HTML)

muralschimap <- leaflet(muralschi) %>%
  addProviderTiles(providers$Stamen.Toner) %>%
  addCircles(fillColor = "tomato", color = "tomato", 
             stroke = FALSE, radius = 175,
              highlightOptions = highlightOptions(fillColor = "lawngreen", 
                                                  fillOpacity = 1),
              popup = ~describe) %>%
  addControl("Mural Locations in Chicago", position = "topright") %>%
  addControl('<a href="https://data.cityofchicago.org/Historic-Preservation/Mural-Registry/we8h-apcf">Data source</a>',
             position = "bottomleft") %>%
  setMaxBounds( lng1 = -87.940101,
                lat1 = 41.643919,
                lng2 = -87.523984,
                lat2 = 42.098388)
muralschimap
```


```{r}
muralschimap2 <- leaflet(cityboundarychi) %>%
  addProviderTiles(providers$Stamen.Toner) %>%
  addPolylines(data = cityboundarychi, stroke = T,
               color = "turquoise", 
               opacity = 1,
               weight = 3)  %>%
  addCircleMarkers(data= muralschi, 
             fill = TRUE,
             radius = 10,
             color = "lawngreen",
             fillOpacity = 0.5, 
             stroke = FALSE,
             label = ~ describe,
             clusterOptions = markerClusterOptions()) %>%
  addControl("Mural Locations in Chicago", position = "topright") %>%
  addControl('<a href="https://data.cityofchicago.org/Historic-Preservation/Mural-Registry/we8h-apcf">Data source</a>',
             position = "bottomleft") %>%
  setMaxBounds( lng1 = -87.940101,
                lat1 = 41.643919,
                lng2 = -87.523984,
                lat2 = 42.098388)
muralschimap2
```



```{r}
muralschimap3 <- leaflet(commareaschi) %>%
  addProviderTiles(providers$Stamen.Toner) %>%
  addPolygons(fillColor = "turquoise", stroke = FALSE,
              label = ~describe) %>%
    addPolylines(data = commareaschi, stroke = T, 
               color = "turquoise", 
               opacity = 1,
               weight = 1.25) %>%
addCircleMarkers(data= muralschi, 
             fill = TRUE,
             radius = 10,
             color = "tomato",
             fillOpacity = 0.5, 
             stroke = FALSE,
             label = ~ describe,
             clusterOptions = markerClusterOptions()) %>%
  addControl("Mural Locations in Chicago", position = "topright") %>%
  addControl('<a href="https://data.cityofchicago.org/Historic-Preservation/Mural-Registry/we8h-apcf">Data source</a>',
             position = "bottomleft") %>%
  setMaxBounds( lng1 = -87.940101,
                lat1 = 41.643919,
                lng2 = -87.523984,
                lat2 = 42.098388)

muralschimap3
```
## TIF Districts in Chicago


```{r load chicago tif data, echo = FALSE}
tifdistrictschi <-st_read("https://data.cityofchicago.org/api/geospatial/fz5x-7zak?method=export&format=GeoJSON")
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.


```{r}
tifdistrictschi$describe <- 
  paste("Name of TIF:", tifdistrictschi$name, "<br>", 
        "TIF Use", tifdistrictschi$use, "<br>",
        "Community Areas for TIF:", tifdistrictschi$comm_area, "<br>") %>% 
  lapply(htmltools::HTML)

tifdistrictschimap <- leaflet(tifdistrictschi) %>%
  addProviderTiles(providers$Stamen.Toner) %>%
  addPolygons(fillColor = "blue", stroke = FALSE,
              highlightOptions = highlightOptions(fillColor = "orange", 
                                                  fillOpacity = 1),
              label = ~describe) %>%
  addControl("Tax Increment Financing (TIF) Districts in Chicago", position = "topright") %>%
  addControl('<a href="https://data.cityofchicago.org/Community-Economic-Development/Boundaries-Tax-Increment-Financing-Districts/fz5x-7zak#revert">Data source</a>',
             position = "bottomleft") %>%
  setMaxBounds( lng1 = -87.805388,
                lat1 = 41.609952,
                lng2 = -87.461107,
                lat2 = 42.027398)

tifdistrictschimap
```

```{r}
tifdistrictschimap2 <- leaflet(commareaschi) %>%
  addProviderTiles(providers$Stamen.Toner) %>%
  addPolygons(fillColor = "orange", stroke = FALSE,
              label = ~describe) %>%
    addPolylines(data = commareaschi, stroke = T, 
               color = "orange", 
               opacity = 1,
               weight = 1.5) %>%
   addPolygons(data = tifdistrictschi,
               fillColor = "blue", fillOpacity = 0.5, stroke = FALSE,
              highlightOptions = highlightOptions(fillColor = "blue", 
                                                  fillOpacity = 3),
              label = ~describe) %>%
  addControl("Tax Increment Financing (TIF) Districts in Chicago", position = "topright") %>%
  addControl('<a href="https://data.cityofchicago.org/Community-Economic-Development/Boundaries-Tax-Increment-Financing-Districts/fz5x-7zak#revert">Data source</a>',
             position = "bottomleft") %>%
  setMaxBounds( lng1 = -87.805388,
                lat1 = 41.609952,
                lng2 = -87.461107,
                lat2 = 42.027398)

tifdistrictschimap2
```


```{r}
saveWidget(muralschimap, file = "chicagomurals.html")
saveWidget(tifdistrictschimap, file = "chicagotifs.html")
saveWidget(muralschimap2, file = "chicagomurals2.html")
saveWidget(tifdistrictschimap2, file = "chicagotifs2.html")
saveWidget(muralschimap3, file = "chicagomurals3.html")
```
